# PACIENTES

###
GET http://localhost:3000/api/pacientes
###
GET http://localhost:3000/api/pacientes/5

###
GET http://localhost:3000/api/pacientes/numSegSocial/998443009


###
POST http://localhost:3000/api/pacientes
Content-Type: application/json

{
  "nombre": "Alfredo",
  "apellidos": "Aparicio Navarro",
  "num_seg_social": "458424242",
  "telefono": "969484254",
  "fecha_registro": "2021-07-30"
}

###
PUT http://localhost:3000/api/pacientes/55
Content-Type: application/json

{
  "nombre": "Adolfo",
  "apellidos": "Aparicio Navarro",
  "num_seg_social": "458424242",
  "telefono": "9694845854",
  "fecha_registro": "2021-07-30"
}

###
DELETE http://localhost:3000/api/pacientes/45

### 
PUT http://localhost:3000/api/pacientes/idPaciente/habitacion/idHabitacion



# Listado de MEDICOS

###
GET http://localhost:3000/api/medicos

# Medico por ID 

###
GET http://localhost:3000/api/medicos/5

###
POST http://localhost:3000/api/medicos
Content-Type: application/json

{
    "nombre": "Agustin",
    "apellidos": "Rivera",
    "especialidad": "Cardiologia",
    "telefono": "55667788"
}

###
PUT http://localhost:3000/api/medicos/45
Content-Type: application/json

{
    "nombre": "Juana",
    "apellidos": "Esteban",
    "especialidad": "Neurofisiologo",
    "telefono": "789654123"
  }




###
DELETE http://localhost:3000/api/medicos/65

###
GET http://localhost:3000/api/pacientes/55/habitacion/5