# PACIENTES

###
GET http://localhost:3000/api/pacientes

###
POST http://localhost:3000/api/pacientes

###
PUT http://localhost:3000/api/pacientes/1

###
DELETE http://localhost:3000/api/pacientes/idPaciente

### 
PUT http://localhost:3000/api/pacientes/idPaciente/habitacion/idHabitacion

# MEDICOS

###
GET http://localhost:3000/api/medicos

###
POST http://localhost:3000/api/medicos

###
PUT http://localhost:3000/api/medicos/1

###
DELETE http://localhost:3000/api/medicos/1