# PACIENTES

###
GET http://localhost:3000/api/pacientes

###
POST http://localhost:3000/api/pacientes
Content-Type: application/json

{
  "nombre": "Alfredo",
  "apellidos": "Aparicio Navarro",
  "num_seg_social": "458424242",
  "telefono": "969484254",
  "fecha_registro": "2021-07-30"
}

###
PUT http://localhost:3000/api/pacientes/1

###
DELETE http://localhost:3000/api/pacientes/idPaciente

### 
PUT http://localhost:3000/api/pacientes/idPaciente/habitacion/idHabitacion

# MEDICOS

###
GET http://localhost:3000/api/medicos

###
POST http://localhost:3000/api/medicos

###
PUT http://localhost:3000/api/medicos/1

###
DELETE http://localhost:3000/api/medicos/1